### PR TITLE
Fix Issue #19 replacing special characters in the title with an empty character

### LINKED ISSUE #19: Books with special characters are not created
If the book has a character, that is not supported by the filesystem for files (typically `? : * / \ " |`), the file is never created if it should appear in the file name.

For example if I have in the shelve this book: https://www.goodreads.com/book/show/21413662-what-if-serious-scientific-answers-to-absurd-hypothetical-questions and want to have the file named `{{title}}`, it is never downloaded.

I suggest create a setting (with default to `-`), for character to replace these special ones, so the file can be created.

Thank you!

### PR DESCRIPTION
**Pull request by riccardopinto**
This PR fixes #19 and adds a simple jest configuration for unit testing.

### CODE REVIEW

**Comment by riccardopinto** [comment]
@MichaBrugger here's the PR :)

**Comment by MichaBrugger** [comment]
Hi @riccardopinto
Thank you again for your work and sorry for answering so late. It's a bit of a tough week, so it might take me a few days before I can go through your PR. I promise to look into it asap (latest on the weekend). I hope that's ok! Have a great week and talk to you soon :)

**Comment by riccardopinto** [comment]
There's no rush, take your time! Thank you :)

**Comment by zacharyw** [comment]
Closing as it was included in another PR

**Pull request closed without merging**
